sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer install --no-interaction

script: make test