security:
    always_authenticate_before_granting: true

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: test
                        roles: 'ROLE_ADMIN'
                    user:
                        password: test
                        roles: 'ROLE_USER'

    firewalls:
        api:
            pattern: ^/
            stateless: true
            anonymous: false
            provider: in_memory
            fos_oauth: false
            http_basic:
                realm: 'Secured Demo Area'