app:
    resource: "@JarvisApiBundle/Controller/DefaultController.php"
    type: annotation

domoticz:
    type: rest
    prefix: domoticz
    resource: "@JarvisApiBundle/Controller/DomoticzController.php"

user:
    type: rest
    resource: "@JarvisApiBundle/Controller/UserController.php"

